init:
  - git config --global core.autocrlf input
  - git config --global core.eol lf

environment:
  matrix:
    - node: "4"
    - node: "5"
    - node: "6"
    - node: "7"

services:
  - mongodb

install:
  - ps: Install-Product node $env:node
  - npm cache clean
  - appveyor-retry npm install

build: off # Disable MSBuilds, not related to the regular build process

test_script:
  - node --version && npm --version
  - cmd: "npm test"

deploy: off
