init:
  - git config --global core.autocrlf input
  - git config --global core.eol lf

environment:
  matrix:
    - node: "5"
    - node: "6"

install:
  - ps: Install-Product node $env:node
  - npm install

build: off # Disable MSBuilds, not related to the regular build process

test_script:
  - node --version && npm --version
  - cmd: "npm test"

deploy: off
