init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off # Disable MSBuilds, not related to the regular build process

test_script:
  - node --version && npm --version
  - cmd: "npm test"

deploy: off
